#!/bin/bash

if [ -f $HOME/.e2node-tester.conf ] ; then
	source $HOME/.e2node-tester.conf
elif [ -f .e2node-tester.conf ] ; then
	source e2node-tester.conf
fi

DOCKER=${DOCKER:-docker}
if [[ $(which ${DOCKER} 2>&1 1>/dev/null) ]] ; then
	echo "${DOCKER} unavailable in the system path."
	echo "Try setting the DOCKER environment variable to a docker implementation."
	echo "DOCKER=/path/to/docker_or_podman ${0} ${@}"
	exit 1
fi

function mount_volume {
	${DOCKER} unshare ${DOCKER} volume mount ${1}
}

function unmount_volume {
	${DOCKER} unshare ${DOCKER} volume unmount ${1}
}

src_vol=${PWD}:/src
if [[ ${DOCKER} == "podman" ]] ; then
	src_vol=${src_vol}:z
fi

${DOCKER} image exists e2node_tester
[[ $? -eq 1 ]] && exit 1

${DOCKER} volume create e2node_ci_results
${DOCKER} run --rm -it -v ${src_vol} -v e2node_ci_results:/results:z e2node_tester:latest $@
[[ $? -eq 1 ]] && exit 1

# For automated tests, save the results
if [ -z "$@" ] ; then
	MNT_PATH=$(mount_volume e2node_ci_results)
	COPY_PATH=${TEST_OUTPUT_DIR}/results/$(date -Iseconds)
	mkdir -p ${COPY_PATH}
	cp -r $MNT_PATH/* ${COPY_PATH}
	unmount_volume e2node_ci_results
	${DOCKER} volume export e2node_ci_results | gzip > ${COPY_PATH}/results-volume.gz
	${DOCKER} volume rm e2node_ci_results

	echo "============= SUMMARY ============="
	echo "========== CODE COVERAGE =========="
	cat ${COPY_PATH}/gcovr-summary.txt
	echo
	echo "========== MEMORY LEAKS ==========="
	sed -n '/<errorcounts>/,/<\/errorcounts>/p' ${COPY_PATH}/valgrind-result.xml
fi
